# -*- coding: utf-8 -*-
"""promotion_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gS8ErtzyrfIFxUHAYSRUfcTmYD_CZJUv
"""

# ------------------------------------------------------------
# 🎯 HR Promotions Dashboard (Works only with Final_Promotions_Predicted_Dataset.csv)
# ------------------------------------------------------------

import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(page_title="HR Promotions Dashboard", layout="wide")
st.title("📊 HR Promotions Analytics Dashboard")

# ------------------------------------------
# Load dataset
# ------------------------------------------
file_name = "Final_Promotions_Predicted_Dataset.csv"
if not os.path.exists(file_name):
    st.error(f"CSV file '{file_name}' NOT found in app folder.")
    st.stop()

df = pd.read_csv(file_name)

# ------------------------------------------
# Auto detect column names by keyword matching
# ------------------------------------------
columns = {c.lower().strip(): c for c in df.columns}

# Promotion result column
promotion_col = next((v for k, v in columns.items() if "predict" in k), None)

# Department column
department_col = next((v for k, v in columns.items() if "dept" in k or "department" in k), None)

# Gender column
gender_col = next((v for k, v in columns.items() if "gender" in k or "sex" in k), None)

# Numeric probability column (optional)
prob_col = next((v for k, v in columns.items() if "prob" in k or "score" in k), None)

# Safety checks
if promotion_col is None:
    st.error("❌ Could not find promotion/prediction column (should contain the word 'predict').")
    st.stop()

# Convert 0/1 to Yes/No if needed
df[promotion_col] = df[promotion_col].replace({1: "Yes", 0: "No"})

# ------------------------------------------
# Filters
# ------------------------------------------
st.sidebar.header("🔍 Filters")
filtered = df.copy()

if department_col:
    d = st.sidebar.multiselect("Department", df[department_col].unique())
    if d:
        filtered = filtered[filtered[department_col].isin(d)]

if gender_col:
    g = st.sidebar.multiselect("Gender", df[gender_col].unique())
    if g:
        filtered = filtered[filtered[gender_col].isin(g)]

# ------------------------------------------
# KPI Cards
# ------------------------------------------
total = len(filtered)
promoted = filtered[promotion_col].eq("Yes").sum()

c1, c2, c3 = st.columns(3)
c1.metric("Total Employees", total)
c2.metric("Promoted Employees", promoted)
c3.metric("Promotion %", f"{(promoted / total * 100):.2f}%")

st.markdown("---")

# ------------------------------------------
# Visuals
# ------------------------------------------
if department_col:
    st.subheader("Promotion by Department")
    st.plotly_chart(px.histogram(
        filtered, x=department_col, color=promotion_col, barmode="group"
    ), use_container_width=True)

if gender_col:
    st.subheader("Promotion by Gender")
    st.plotly_chart(px.histogram(
        filtered, x=gender_col, color=promotion_col, barmode="group"
    ), use_container_width=True)

if prob_col and "Satisfaction" in df.columns and "Performance" in df.columns:
    st.subheader("Promotion Probability Heatmap")
    st.plotly_chart(px.density_heatmap(
        filtered, x="Satisfaction", y="Performance", z=prob_col
    ), use_container_width=True)

# ------------------------------------------
# Table + Download
# ------------------------------------------
st.markdown("---")
st.subheader("📋 Dataset Preview")
st.dataframe(filtered, use_container_width=True)

csv = filtered.to_csv(index=False).encode("utf-8")
st.download_button("⬇ Download Filtered Dataset", data=csv,
                   file_name="Filtered_Promotions.csv", mime="text/csv")
