# -*- coding: utf-8 -*-
"""promotion_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gS8ErtzyrfIFxUHAYSRUfcTmYD_CZJUv
"""

# ------------------------------------------------------------
# 🎯 HR Promotions Dashboard (Works only with Final_Promotions_Predicted_Dataset.csv)
# ------------------------------------------------------------

import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(page_title="HR Promotions Dashboard", layout="wide")
st.title("📊 HR Promotions Analytics Dashboard")

# -----------------------------------------------------------
# Load dataset
# -----------------------------------------------------------
file_name = "Final_Promotions_Predicted_Dataset.csv"
if not os.path.exists(file_name):
    st.error(f"CSV file '{file_name}' NOT found in app folder.")
    st.stop()

df = pd.read_csv(file_name)

# -----------------------------------------------------------
# Auto-detect frequently used columns
# -----------------------------------------------------------
columns = {c.lower().strip(): c for c in df.columns}

promotion_col  = next((v for k, v in columns.items() if "predict" in k), None)
dept_col       = next((v for k, v in columns.items() if "dept" in k or "department" in k), None)
gender_col     = next((v for k, v in columns.items() if "gender" in k or "sex" in k), None)
prob_col       = next((v for k, v in columns.items() if "prob" in k or "score" in k), None)
exp_col        = next((v for k, v in columns.items() if "experience" in k or "exp" in k), None)
salary_col     = next((v for k, v in columns.items() if "salary" in k or "ctc" in k or "income" in k), None)
age_col        = next((v for k, v in columns.items() if "age" in k or "tenure" in k or "service" in k), None)

# Convert 0/1 to Yes/No if needed
df[promotion_col] = df[promotion_col].replace({1: "Yes", 0: "No"})

# -----------------------------------------------------------
# Filters
# -----------------------------------------------------------
filtered = df.copy()
st.sidebar.header("🔍 Filters")

if dept_col:
    d = st.sidebar.multiselect("Department", df[dept_col].unique())
    if d: filtered = filtered[filtered[dept_col].isin(d)]

if gender_col:
    g = st.sidebar.multiselect("Gender", df[gender_col].unique())
    if g: filtered = filtered[gender_col].isin(g)]

# -----------------------------------------------------------
# KPI Cards
# -----------------------------------------------------------
total = len(filtered)
promoted = filtered[promotion_col].eq("Yes").sum()
not_promoted = total - promoted
promotion_rate = (promoted / total * 100) if total > 0 else 0

c1, c2, c3, c4 = st.columns(4)
c1.metric("Total Employees", total)
c2.metric("Promoted Employees", promoted)
c3.metric("Not Promoted", not_promoted)
c4.metric("Promotion %", f"{promotion_rate:.2f}%")

st.markdown("---")

# -----------------------------------------------------------
# 🎨 Visuals (6 with different colors)
# -----------------------------------------------------------

# 1 Promotion by Department
if dept_col:
    st.subheader("📌 Promotion by Department")
    fig1 = px.histogram(
        filtered, x=dept_col, color=promotion_col, barmode="group",
        color_discrete_sequence=["#0072B2", "#D55E00"]
    )
    st.plotly_chart(fig1, use_container_width=True)

# 2 Promotion by Gender
if gender_col:
    st.subheader("📌 Promotion by Gender")
    fig2 = px.histogram(
        filtered, x=gender_col, color=promotion_col, barmode="group",
        color_discrete_sequence=["#009E73", "#CC79A7"]
    )
    st.plotly_chart(fig2, use_container_width=True)

# 3 Promotion by Experience
if exp_col:
    st.subheader("📌 Promotion by Experience")
    fig3 = px.box(
        filtered, x=promotion_col, y=exp_col, points="all",
        color=promotion_col, color_discrete_sequence=["#F0E442", "#56B4E9"]
    )
    st.plotly_chart(fig3, use_container_width=True)

# 4 Promotion by Salary Range
if salary_col:
    st.subheader("📌 Promotion by Salary Range")
    fig4 = px.histogram(
        filtered, x=salary_col, color=promotion_col, nbins=25,
        color_discrete_sequence=["#E69F00", "#0072B2"]
    )
    st.plotly_chart(fig4, use_container_width=True)

# 5 Promotion by Age / Tenure
if age_col:
    st.subheader("📌 Promotion by Age / Tenure")
    fig5 = px.box(
        filtered, x=promotion_col, y=age_col, points="all",
        color=promotion_col, color_discrete_sequence=["#009E73", "#D55E00"]
    )
    st.plotly_chart(fig5, use_container_width=True)

# 6 Promotion Probability Distribution (if exists)
if prob_col:
    st.subheader("📌 Promotion Probability Distribution")
    fig6 = px.histogram(
        filtered, x=prob_col, color=promotion_col, nbins=20,
        color_discrete_sequence=["#6A3D9A", "#FF7F00"]
    )
    st.plotly_chart(fig6, use_container_width=True)

st.markdown("---")

# -----------------------------------------------------------
# 🌟 Top 20 Candidates Eligible for Promotion
# -----------------------------------------------------------
if prob_col:
    st.subheader("🏆 Top 20 Most Eligible Employees for Promotion")
    top20 = df.sort_values(prob_col, ascending=False).head(20)
    st.dataframe(top20, use_container_width=True)

st.markdown("---")

# -----------------------------------------------------------
# 🧠 AI-Style Automatic Insights (text only)
# -----------------------------------------------------------
st.subheader("🧠 Key Insights From Promotions Data")

insights = []

if dept_col:
    best_dept = filtered[filtered[promotion_col] == "Yes"][dept_col].mode()
    if not best_dept.empty:
        insights.append(f"🔹 Highest promotions observed in **{best_dept.iloc[0]}** department.")

if gender_col:
    male_rate = filtered[filtered[gender_col] == filtered[gender_col].unique()[0]][promotion_col].eq("Yes").mean()
    female_rate = filtered[filtered[gender_col] == filtered[gender_col].unique()[-1]][promotion_col].eq("Yes").mean()
    if male_rate != female_rate:
        if male_rate > female_rate:
            insights.append("🔹 **Male employees** appear more likely to be promoted.")
        else:
            insights.append("🔹 **Female employees** appear more likely to be promoted.")

if exp_col:
    insights.append("🔹 Higher work experience correlates strongly with promotion probability.")

if salary_col:
    insights.append("🔹 Employees with higher salary ranges show higher promotion likelihood.")

if prob_col:
    insights.append("🔹 Probability model provides strong separation between promoted and non-promoted employees.")

if len(insights) == 0:
    insights.append("🔹 No clear insights detectable from dataset.")

for line in insights:
    st.write(line)

st.markdown("---")

# -----------------------------------------------------------
# Download Dataset (Filtered)
# -----------------------------------------------------------
csv = filtered.to_csv(index=False).encode("utf-8")
st.download_button("⬇ Download Filtered Dataset",
                   data=csv, file_name="Filtered_Promotions.csv", mime="text/csv")
